source "https://rubygems.org"

ruby "3.4.6"

# Web framework
gem "sinatra", "~> 4.1"
gem "sinatra-contrib", "~> 4.1"
gem "puma", "~> 6.0"

# Rake tasks (db:migrate等)
gem "rake"

# Database
gem "sinatra-activerecord", "~> 2.0"
gem "activerecord", "~> 8.0"
gem "pg", "~> 1.5"

# Authentication
gem "bcrypt", "~> 3.1"
gem "jwt", "~> 2.9"

# Image upload
gem "shrine", "~> 3.6"
gem "aws-sdk-s3", "~> 1.170", require: false

# CORS
gem "rack-cors", "~> 2.0"

# JSON
gem "json"

group :development, :test do
  gem "dotenv"
  gem "rerun"
end
